[workspace]
resolver = "2"

members = [
    "shared",
    "web",
    "telegram"
]

[workspace.dependencies]  
serde = { version = "1.0.192", features=["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
